spring:
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://pc-2zetn57r91en7zp46.rwlb.rds.aliyuncs.com:3306/qc?useUnicode=true&characterEncoding=UTF8&useSSL=false&rewriteBatchedStatements=true
    username: qc
    type: com.alibaba.druid.pool.DruidDataSource
    password: Xty@20180217

  redis:
    port: 6379
    database: 1
    lettuce:
      pool:
        max-idle: 500
        min-idle: 0
        max-active: 100
        max-wait: -1ms
    timeout: 1s
    host: r-2zewzyyljgmoukw97p.redis.rds.aliyuncs.com
    password: u^v!gRCoJ%o232y$
  cache:
    redis:
      use-key-prefix: true
      time-to-live: 60s

logging:
  config: classpath:logback-prod.xml
  level:
    root: info

user:
  defaultAvatars:
    - https://face-images.oss-cn-beijing.aliyuncs.com/%e5%a4%b4%e5%83%8f%e9%a3%8e%e6%99%af.png
    - https://face-images.oss-cn-beijing.aliyuncs.com/%e5%a4%b4%e5%83%8f%e9%a3%8e%e6%99%af.png
    - https://face-images.oss-cn-beijing.aliyuncs.com/%e5%a4%b4%e5%83%8f%e9%a3%8e%e6%99%af.png
    - https://face-images.oss-cn-beijing.aliyuncs.com/%e5%a4%b4%e5%83%8f%e9%a3%8e%e6%99%af.png

tlsSig:
  admin: admin
  apkAppId: 1400203105
  pubStr: |
    -----BEGIN PUBLIC KEY-----
    MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE6SgnuAuN+H/qiyqU/9gUUEPTS81h
    4rHkTNAJ/qwlPvpKXGdxH7prxGEUHTO2nSjDlm9O13rCL4SuVfmSzeCzXA==
    -----END PUBLIC KEY-----
  privStr: |
    -----BEGIN PRIVATE KEY-----
    MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgR4Bvwh/e6LIcGeXO
    sVD4AUMqPBYoYNtwaf15qnWIw6GhRANCAATpKCe4C434f+qLKpT/2BRQQ9NLzWHi
    seRM0An+rCU++kpcZ3EfumvEYRQdM7adKMOWb07XesIvhK5V+ZLN4LNc
    -----END PRIVATE KEY-----
  registTlsUserUrl: https://console.tim.qq.com/v4/im_open_login_svc/account_import
  modifyTlsUserUrl: https://console.tim.qq.com/v4/profile/portrait_set
WeChat:
  loginUrl: https://api.weixin.qq.com/sns/jscode2session
  appid: wx8d04ad0492dab24d
  secret: 0369106e59bf15d680c54418d4a59b48
  grant_type: authorization_code
Amap:
  coordinateConvertUrl: https://restapi.amap.com/v3/assistant/coordinate/convert
  placeAroundUrl: https://restapi.amap.com/v3/place/around
  amapKey: d05450f970ae57957f7d56b82cebdeaa

dubbo:
  provider:
    version: 1.0
  application:
    name: feeds
  scan:
    base-packages: com.quantumtime.qc.service
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://172.17.21.149:2181?backup=172.17.21.150:2181,172.17.21.151:2181
#    address: zookeeper://127.0.0.1:2181
#    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache
sensorsdata:
  path: data/access_log
  flush: 1
rocketmq:
  accesskey-id: LTAI4FkRyuiscF9KBsjTFj5y
  accesskey-secret: syUfwbVIx0wCkbWB2Yz70YoSWiXVrQ
  namesrv: http://MQ_INST_1831423916153787_BbeLCwus.cn-beijing.mq-internal.aliyuncs.com:8080
  # 生产者配置
  producer:
    group: GID-qc-api
    qualify:
      topic: qualify
      tag: request
    feeds:
      topic: feeds
      tag: request
recommend:
  url: http://172.17.130.10:8004/recommender/getfeedsandarticle
aliyun:
  vodCallbackUrl: https://api.milinzone.com/feeds/video/callback

#xxl_job配置

xxl:
  job:
    accessToken: omksdvsd213ad
    admin:
      addresses: http://172.17.130.10:8090/xxl-job-admin
    executor:
      appname: qc-api
      ip: ''
      logpath: /data/applogs/xxl-job/qcServer
      logretentiondays: 7
      port: 4545
